[package]
name = "libc-stdhandle"
description = "Helper functions for retrieving stdin, stdout, stderr."
edition = "2024"
version = "0.1.1"
authors = ["CrLF0710 <crlf0710@gmail.com>", "Aaron Perez <aap7640@gmail.com>"]
license = "MIT/Apache-2.0"
build = "build.rs"
repository = "https://github.com/crlf0710/libc-stdhandle"
documentation = "https://docs.rs/libc-stdhandle"

[dependencies]
libc = { version = "0.2.189", default-features = false }

[build-dependencies]
cc = "1"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
